# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    # Have an easy way to get the root of the project
    def root_path
      Dir.pwd.sub(/.*\Kfastlane/, '').sub(/.*\Kandroid/, '').sub(/.*\Kios/, '').sub(/.*\K\/\//, '')
    end
  # Have an easy way to run flutter tasks on the root of the project
  lane :sh_on_root do |options|
    command = options[:command]
    sh("cd #{root_path} && #{command}")
  end

  private_lane :build_apk do
    env = ENV['ANDROID_SCHEME']

    params = env == "dev" ? '--dart-define FLAVOR="dev" -t lib/main.dart ' : '--dart-define FLAVOR="prod" -t lib/main.dart '

    desc "Building #{env} Android APK"
    sh_on_root(command: "fvm use #{ENV['FLUTTER_VERSION']} && fvm flutter build apk --split-per-abi #{params}")
  end



  lane :deploy_staging do
    build_apk

    firebase_app_distribution(
      app: ENV['ANDROID_FIREBASE_APP_DISTRIBUTION_APP'],
      testers: ENV['ANDROID_FIREBASE_APP_DISTRIBUTION_TESTERS'],
      android_artifact_type: "APK",
      android_artifact_path: "#{root_path}/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk",
      release_notes: ENV['ANDROID_FIREBASE_APP_DISTRIBUTION_RELEASE_NOTES'],
      service_credentials_file: ENV['ANDROID_FIREBASE_APP_DISTRIBUTION_CREDENTIALS_FILE_PATH'],
    )
  end

end
